global:
  hosts:
    domain: localhost
    https: false
  edition: ce
  ingress:
    enabled: false
  
  # Disable everything not needed
  minio:
    enabled: false
  grafana:
    enabled: false
  kas:
    enabled: false
  registry:
    enabled: false
  appConfig:
    artifacts:
      enabled: false
    lfs:
      enabled: false
    uploads:
      enabled: false
    packages:
      enabled: false
    backups:
      enabled: false
      bucket: gitlab-backups
      tmpBucket: gitlab-tmp

certmanager:
  enabled: false

certmanager-issuer:
  email: admin@localhost.com

prometheus:
  enabled: false

nginx-ingress:
  enabled: false

gitlab-runner:
  enabled: false

registry:
  enabled: false

gitlab:
  toolbox:
    backups:
      objectStorage:
        config:
          secret: gitlab-object-storage
          key: connection
  
  sidekiq:
    resources:
      requests:
        memory: 500Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 500m
    minReplicas: 1
    maxReplicas: 1
  
  webservice:
    resources:
      requests:
        memory: 600Mi
        cpu: 200m
      limits:
        memory: 1.2Gi
        cpu: 400m
    minReplicas: 1
    maxReplicas: 1
  
  gitaly:
    persistence:
      enabled: false
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
      limits:
        memory: 400Mi
        cpu: 200m
  
  gitlab-shell:
    resources:
      requests:
        memory: 50Mi
        cpu: 50m
      limits:
        memory: 100Mi
        cpu: 100m

  migrations:
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
      limits:
        memory: 400Mi
        cpu: 200m

postgresql:
  install: true
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 400Mi
      cpu: 200m
  persistence:
    enabled: false
  metrics:
    enabled: false

redis:
  install: true
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
      cpu: 100m
  master:
    persistence:
      enabled: false
  metrics:
    enabled: false