# Charts config: https://docs.gitlab.com/charts/charts/
# Global config: https://docs.gitlab.com/charts/charts/globals/  
# Minimal config

global:
  edition: ce
  hosts:
    domain: localhost
  
  ingress:
    enabled: false
    class: traefik
    configureCertmanager: false
    
  image:
    pullPolicy: IfNotPresent

  # Disable optional global services
  kas:
    enabled: false
  
  grafana:
    enabled: false
  
  minio:
    enabled: false

  appConfig:
    lfs:
      enabled: false
      bucket: git-lfs
    artifacts:
      enabled: false
      bucket: gitlab-artifacts
    uploads:
      enabled: false
      bucket: gitlab-uploads
    packages:
      enabled: false
      bucket: gitlab-packages
    externalDiffs:
      enabled: false
    terraformState:
      enabled: false
    dependencyProxy:
      enabled: false

certmanager-issuer:
  email: admin@localhost.com

nginx-ingress:
  enabled: false

# Disable registry at top level
registry:
  enabled: false

# Disable prometheus at top level
prometheus:
  install: false

# Disable GitLab Runner at top level
gitlab-runner:
  install: false

gitlab:
  gitlab-shell:
    service:
      type: NodePort
      nodePort: 32222
    replicas: 1
    maxReplicas: 1
    minReplicas: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 25m
      limits:
        memory: 128Mi
        cpu: 50m

  gitaly:
    replicas: 1
    persistence:
      enabled: false
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 200Mi
        cpu: 100m

  webservice:
    replicas: 1
    maxReplicas: 1
    minReplicas: 1
    workerProcesses: 1
    resources:
      requests:
        memory: 300Mi
        cpu: 100m
      limits:
        memory: 600Mi
        cpu: 200m

  sidekiq:
    replicas: 1
    maxReplicas: 1
    minReplicas: 1
    resources:
      requests:
        memory: 300Mi
        cpu: 100m
      limits:
        memory: 600Mi
        cpu: 200m

  migrations:
    replicas: 1
    maxReplicas: 1
    minReplicas: 1
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 100m

  # Disable optional gitlab components
  gitlab-exporter:
    enabled: false
  
  toolbox:
    enabled: false

postgresql:
  install: true
  primary:
    persistence:
      enabled: false
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 100m

redis:
  install: true
  master:
    persistence:
      enabled: false
    resources:
      requests:
        memory: 64Mi
        cpu: 25m
      limits:
        memory: 128Mi
        cpu: 50m