Vagrant.configure("2") do |config|
 config.vm.box = "generic/alpine312"
  config.vm.box_check_update = false
  
  # Fix SSH key permissions issue on shared folders
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]

  # Server VM (K3s Controller)
  SERVER_HOSTNAME = "thi-leS"
  SERVER_IP = "192.168.56.110"
  config.vm.define SERVER_HOSTNAME do |server|
    server.vm.hostname = SERVER_HOSTNAME
    server.vm.network "private_network", ip: SERVER_IP

        server.vm.network "forwarded_port", guest: 80, host: 8080
    # creates the network configuration for eth1 and restarts the networking service
    server.vm.provision "shell", run: "always", inline: <<-SHELL
      echo "==> Ensuring network interface eth1 is configured and up..."
      
      sudo mkdir -p /etc/network/interfaces.d

      # Create the configuration file for eth1 with a static IP
      echo 'auto eth1' | sudo tee /etc/network/interfaces.d/eth1
      echo 'iface eth1 inet static' | sudo tee -a /etc/network/interfaces.d/eth1
      echo "  address #{SERVER_IP}" | sudo tee -a /etc/network/interfaces.d/eth1
      echo '  netmask 255.255.255.0' | sudo tee -a /etc/network/interfaces.d/eth1
      
      sudo /etc/init.d/networking restart
    SHELL

    server.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = SERVER_HOSTNAME
    end
    # runs the main setup script to install K3s and deploy the applications.
    server.vm.provision "shell", path: "scripts/setup_server.sh"
  end
end