Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine312"
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]

  SERVER_HOSTNAME = "thi-leS"
  SERVER_IP = "192.168.56.110"
  WORKER_HOSTNAME = "thi-leSW"
  WORKER_IP = "192.168.56.111"

  config.vm.define SERVER_HOSTNAME do |server|
    server.vm.hostname = SERVER_HOSTNAME
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = SERVER_HOSTNAME
    end
    server.vm.provision "shell", path: "scripts/setup_server.sh"
  end

  config.vm.define WORKER_HOSTNAME do |worker|
    worker.vm.hostname = WORKER_HOSTNAME
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
      vb.name = WORKER_HOSTNAME
    end
    worker.vm.provision "shell", path: "scripts/setup_worker.sh"
  end
end